site_name: 【布客】PyTorch 中文翻译
site_url: https://pytorch.apachecn.org

# Repository
repo_name: apachecn/pytorch-doc-zh
repo_url: https://github.com/apachecn/pytorch-doc-zh

theme:
  name: material
  custom_dir: themes
  locale: zh_CN
  analytics:
    gtag: G-8DP4GX97XY
  features:
    - content.code.copy
    - content.action.edit
    - content.action.view
    - navigation.footer

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - "PyTorch 中文文档 & 教程": "index.md"
  - "PyTorch 1.0 中文文档 & 教程": 
    - "目录": "1.0/README.md"
    - "中文教程":
      - "入门":
        - "PyTorch 深度学习: 60 分钟极速入门":
          - "介绍": "1.0/deep_learning_60min_blitz.md"
          - "什么是 PyTorch？": "1.0/blitz_tensor_tutorial.md"
          - "Autograd：自动求导": "1.0/blitz_autograd_tutorial.md"
          - "神经网络": "1.0/blitz_neural_networks_tutorial.md"
          - "训练分类器": "1.0/blitz_cifar10_tutorial.md"
          - "可选：数据并行处理": "1.0/blitz_data_parallel_tutorial.md"
        - "数据加载和处理教程": "1.0/data_loading_tutorial.md"
        - "用例子学习 PyTorch": "1.0/pytorch_with_examples.md"
        - "迁移学习教程": "1.0/transfer_learning_tutorial.md"
        - "混合前端的 seq2seq 模型部署": "1.0/deploy_seq2seq_hybrid_frontend_tutorial.md"
        - "Saving and Loading Models": "1.0/saving_loading_models.md"
        - "What is torch.nn really?": "1.0/nn_tutorial.md"
      - "图像":
        - "Torchvision 模型微调": "1.0/finetuning_torchvision_models_tutorial.md"
        - "空间变换器网络教程": "1.0/spatial_transformer_tutorial.md"
        - "使用 PyTorch 进行图像风格转换": "1.0/neural_style_tutorial.md"
        - "对抗性示例生成": "1.0/fgsm_tutorial.md"
        - "使用 ONNX 将模型从 PyTorch 传输到 Caffe2 和移动端": "1.0/super_resolution_with_caffe2.md"
      - "文本":
        - "聊天机器人教程": "1.0/chatbot_tutorial.md"
        - "使用字符级别特征的 RNN 网络生成姓氏": "1.0/char_rnn_generation_tutorial.md"
        - "使用字符级别特征的 RNN 网络进行姓氏分类": "1.0/char_rnn_classification_tutorial.md"
        - "Deep Learning for NLP with Pytorch": 
          - "在深度学习和 NLP 中使用 Pytorch": "1.0/deep_learning_nlp_tutorial.md"
          - "PyTorch 介绍": "1.0/nlp_pytorch_tutorial.md"
          - "使用 PyTorch 进行深度学习": "1.0/nlp_deep_learning_tutorial.md"
          - "Word Embeddings: Encoding Lexical Semantics": "1.0/nlp_word_embeddings_tutorial.md"
          - "序列模型和 LSTM 网络": "1.0/nlp_sequence_models_tutorial.md"
          - "Advanced: Making Dynamic Decisions and the Bi-LSTM CRF": "1.0/nlp_advanced_tutorial.md"
        - "基于注意力机制的 seq2seq 神经网络翻译": "1.0/seq2seq_translation_tutorial.md"
      - "生成":
        - "DCGAN Tutorial": "1.0/dcgan_faces_tutorial.md"
      - "强化学习":
        - "Reinforcement Learning (DQN) Tutorial": "1.0/reinforcement_q_learning.md"
      - "扩展 PyTorch":
        - "用 numpy 和 scipy 创建扩展": "1.0/numpy_extensions_tutorial.md"
        - "Custom C-- and CUDA Extensions": "1.0/cpp_extension.md"
        - "Extending TorchScript with Custom C-- Operators": "1.0/torch_script_custom_ops.md"
      - "生产性使用":
        - "Writing Distributed Applications with PyTorch": "1.0/dist_tuto.md"
        - "使用 Amazon AWS 进行分布式训练": "1.0/aws_distributed_training_tutorial.md"
        - "ONNX 现场演示教程": "1.0/ONNXLive.md"
        - "在 C-- 中加载 PYTORCH 模型": "1.0/cpp_export.md"
      - "其它语言中的 PyTorch":
        - "使用 PyTorch C-- 前端": "1.0/cpp_frontend.md"
    - "中文文档":
      - "注解":
        - "自动求导机制": "1.0/notes_autograd.md"
        - "广播语义": "1.0/notes_broadcasting.md"
        - "CUDA 语义": "1.0/notes_cuda.md"
        - "Extending PyTorch": "1.0/notes_extending.md"
        - "Frequently Asked Questions": "1.0/notes_faq.md"
        - "Multiprocessing best practices": "1.0/notes_multiprocessing.md"
        - "Reproducibility": "1.0/notes_randomness.md"
        - "Serialization semantics": "1.0/notes_serialization.md"
        - "Windows FAQ": "1.0/notes_windows.md"
      - "包参考":
        - "torch": 
          - "介绍": "1.0/torch.md"
          - "Tensors": "1.0/torch_tensors.md"
          - "Random sampling": "1.0/torch_random_sampling.md"
          - "Serialization, Parallelism, Utilities": "1.0/torch_serialization_parallelism_utilities.md"
          - "Math operations":
            - "Pointwise Ops": "1.0/torch_math_operations_pointwise_ops.md"
            - "Reduction Ops": "1.0/torch_math_operations_reduction_ops.md"
            - "Comparison Ops": "1.0/torch_math_operations_comparison_ops.md"
            - "Spectral Ops": "1.0/torch_math_operations_spectral_ops.md"
            - "Other Operations": "1.0/torch_math_operations_other_ops.md"
            - "BLAS and LAPACK Operations": "1.0/torch_math_operations_blas_lapack_ops.md"
        - "torch.Tensor": "1.0/tensors.md"
        - "Tensor Attributes": "1.0/tensor_attributes.md"
        - "数据类型信息": "1.0/type_info.md"
        - "torch.sparse": "1.0/sparse.md"
        - "torch.cuda": "1.0/cuda.md"
        - "torch.Storage": "1.0/storage.md"
        - "torch.nn": "1.0/nn.md"
        - "torch.nn.functional": "1.0/nn_functional.md"
        - "torch.nn.init": "1.0/nn_init.md"
        - "torch.optim": "1.0/optim.md"
        - "Automatic differentiation package - torch.autograd": "1.0/autograd.md"
        - "Distributed communication package - torch.distributed": "1.0/distributed.md"
        - "Probability distributions - torch.distributions": "1.0/distributions.md"
        - "Torch Script": "1.0/jit.md"
        - "多进程包 - torch.multiprocessing": "1.0/multiprocessing.md"
        - "torch.utils.bottleneck": "1.0/bottleneck.md"
        - "torch.utils.checkpoint": "1.0/checkpoint.md"
        - "torch.utils.cpp_extension": "1.0/docs_cpp_extension.md"
        - "torch.utils.data": "1.0/data.md"
        - "torch.utils.dlpack": "1.0/dlpack.md"
        - "torch.hub": "1.0/hub.md"
        - "torch.utils.model_zoo": "1.0/model_zoo.md"
        - "torch.onnx": "1.0/onnx.md"
        - "Distributed communication package (deprecated) - torch.distributed.deprecated": "1.0/distributed_deprecated.md"
      - "torchvision 参考": 
        - "目录": "1.0/docs_torchvision_ref.md"
        - "torchvision.datasets": "1.0/torchvision_datasets.md"
        - "torchvision.models": "1.0/torchvision_models.md"
        - "torchvision.transforms": "1.0/torchvision_transforms.md"
        - "torchvision.utils": "1.0/torchvision_utils.md"
  - "贡献者": "contrib.md"
  - "关于我们": "https://www.apachecn.org/about/"
  - "中文资源合集": "https://docs.apachecn.org"
